package b.c.a;

@Deprecated
/* compiled from: FeatureParserWrapper */
public class g {
    public static final String Ai = "support_3d_face_beauty";
    public static final String Bi = "support_mi_face_beauty";
    public static final String Ci = "enable_algorithm_in_file_suffix";
    public static final String Dh = "is_pad";
    public static final String Di = "support_camera_dynamic_light_spot";
    public static final String Eh = "support_dual_sd_card";
    public static final String Ei = "support_super_resolution";
    public static final String Fh = "support_edge_handgrip";
    public static final String Fi = "support_realtime_manual_exposure_time";
    public static final String Gh = "fp_nav_event_name_list";
    public static final String Gi = "support_picture_watermark";
    public static final String HIBERNATION_TIMEOUT = "camera_hibernation_timeout_in_minutes";
    public static final String Hh = "support_camera_shader_effect";
    public static final String Hi = "support_camera_role";
    public static final String IS_HONGMI = "is_hongmi";
    public static final String IS_XIAOMI = "is_xiaomi";
    public static final String Ih = "support_camera_burst_shoot";
    public static final String Ii = "sensor_has_latency";
    public static final String Jh = "burst_shoot_count";
    public static final String Ji = "fpsList";
    public static final String Kh = "support_camera_movie_solid";
    public static final String Lh = "support_camera_skin_beauty";
    public static final String Mh = "support_camera_record_location";
    public static final String Nh = "support_camera_water_mark";
    public static final String Oh = "support_camera_new_style_time_water_mark";
    public static final String Ph = "support_camera_video_pause";
    public static final String Qh = "support_camera_boost_brightness";
    public static final String Rh = "support_camera_aohdr";
    public static final String Sh = "support_chroma_flash";
    public static final String Th = "support_object_track";
    public static final String Uh = "support_camera_4k_quality";
    public static final String VENDOR = "vendor";
    public static final String Vh = "camera_supported_asd";
    public static final String Wh = "is_camera_replace_higher_cost_effect";
    public static final String Xh = "support_camera_manual_function";
    public static final String Yh = "support_camera_torch_capture";
    public static final String Zh = "is_camera_hold_blur_background";
    public static final String _h = "support_camera_peaking_mf";
    public static final String bi = "support_camera_gradienter";
    public static final String di = "is_camera_lower_qrscan_frequency";
    public static final String ei = "is_camera_preview_with_subthread_looper";
    public static final String fi = "camera_reduce_preview_flag";
    public static final String gi = "camera_exposure_compensation_steps_num";
    public static final String hi = "is_camera_app_water_mark";
    public static final String ii = "support_camera_tilt_shift";
    public static final String ji = "support_camera_quick_snap";
    public static final String ki = "support_front_flash";
    public static final String li = "is_camera_isp_rotated";
    public static final String mi = "front_fingerprint_sensor";
    public static final String ni = "is_18x9_ratio_screen";
    public static final String oi = "is_front_video_quality_1080p";
    public static final String qi = "is_video_snapshot_size_limit";
    public static final String ri = "is_surface_size_limit";
    public static final String ti = "is_hal_does_caf_when_flash_on";
    public static final String ui = "is_support_stereo";
    public static final String vi = "is_support_optical_zoom";
    public static final String wi = "is_rgb888_egl_prefer";
    public static final String xi = "support_screen_light";
    public static final String yi = "support_psensor_pocket_mode";
    public static final String zi = "support_front_beauty_mfnr";
}
